### ISSUE TITLE
The workflow isn't working when I hit enter

### ISSUE THREAD

**Issue by BeMrTeal** [mr-pennyworth/alfred-meta-ai-flash-imagine#1]
I installed Alfred Extra Pane, followed the tutorials and the Meta AI won't work. I have to click in the submit button on the meta prompt.

![Screenshot 2024-11-04 at 15 36 28](https://github.com/user-attachments/assets/85f53f38-d3b6-49c1-a597-8f58ffe7d8be)
![Screenshot 2024-11-04 at 15 36 57](https://github.com/user-attachments/assets/8b0364c7-25f5-4456-bd46-fdfc24d4400d)

**Comment by mr-pennyworth** [comment]
@BeMrTeal just wanted to confirm, have you logged into your facebook account inside the extra pane?
https://github.com/mr-pennyworth/alfred-meta-ai-flash-imagine?tab=readme-ov-file#first-use-facebook-login

**Comment by BeMrTeal** [comment]
> @BeMrTeal just wanted to confirm, have you logged into your facebook account inside the extra pane? https://github.com/mr-pennyworth/alfred-meta-ai-flash-imagine?tab=readme-ov-file#first-use-facebook-login

Yes I did :)

**Comment by mr-pennyworth** [comment]
@BeMrTeal hmm interesting!
Trying to figure out what it could be... 🤔
(when I used the workflow today after a long time, I had the same problem, and realized that I needed to log in).

Since you're logged-in, wondering what could be the problem...
Maybe the flash generation isn't available to UK users?

Can you confirm, in your Safari, after you log in, if you type "imagine warhammer 40k ork", you do get the flash-generated image without hitting enter?

**Comment by BeMrTeal** [comment]
No, I need to hit enter.

**Comment by mr-pennyworth** [comment]
@BeMrTeal that explains it! Looks like Meta's "Generate images as you type" isn't available for your account (likely it isn't available in UK / EU at all)

I'll go ahead and close this as there's nothing we can do about it :(
